language: android
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.2
    - android-26
  licenses:
    - '.+'

notifications:
  email:
    on_success: never
    on_failure: change