language: android
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.2
    - android-26
  licenses:
    - '.+'

env:
  global:
    # Don't worry, they're fake :)
    - ETHEREUM_INFURA="https://ropsten.infura.io/NoXjb7h7L0YPzNSbroLJ"
    - ETHEREUM_WALLET_PASSWORD="extremepassword"
    - ETHEREUM_WALLET_FILE="~/UTC--2018-01-11T18-58-12.059Z--0121a28a3a04a71bd11f4749ca23f2585b4844d5"
    - ETHEREUM_ATTENDANCE_TRACKER_ADDRESS = "0x324f85e86b1c42f24894c31aef1d74360ef8607e"
    - ETHEREUM_ATTENDANCE_TRACKER_URL="https://ropsten.etherscan.io/address/0x324f85e86b1c42f24894c31aef1d74360ef8607e"

notifications:
  email:
    on_success: never
    on_failure: change