swagger: '2.0'
info:
  version: "2.0.0"
  title: Kleo Classes and Passes Management API
  description: The API provides endpoints for managing users, courses, sessions and passes.

basePath: /api
schemes:
  - http
produces:
  - "application/vnd.tum.aes.kleo.v2+json"

securityDefinitions:
  OAuth2Password:
    type: oauth2
    flow: password
    tokenUrl: "oauth/token"
    scopes:
      management: "Endpoints for managing users, courses, sessions and passes"

tags:
- name: "courses"
- name: "users"
- name: "sessions"
- name: "tutors"
- name: "passes"
- name: "attendances"

paths:
  /courses:
    get:
      tags:
        - courses
      operationId: getCourses
      security:
        - OAuth2Password: [management]
      responses:
        200:
          description: A list of entities
          schema:
            type: array
            minItems: 0
            items:
              $ref: '#/definitions/CourseDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
    post:
      tags:
        - courses
      operationId: addCourse
      security:
        - OAuth2Password: [management]
      parameters:
      - in: body
        name: course
        schema:
          $ref: '#/definitions/CourseDTO'
      responses:
        201:
          description: An entity created
          schema:
            $ref: '#/definitions/CourseDTO'
        400:
          description: Problem with the request, such as a missing, invalid or type mismatched parameter
          schema:
            $ref: '#/definitions/ErrorDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /courses/{courseId}:
    get:
      tags:
        - courses
      operationId: getCourse
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
      responses:
        200:
          description: An entity requested
          schema:
            $ref: '#/definitions/CourseDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
    put:
      tags:
        - courses
      operationId: updateCourse
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
        - in: body
          name: course
          schema:
            $ref: '#/definitions/CourseDTO'
      responses:
        200:
          description: A updated entity
          schema:
            $ref: '#/definitions/CourseDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
    delete:
      tags:
        - courses
      operationId: "deleteCourse"
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
      responses:
        204:
          description: Entity has been deleted sucessufly
        404:
          description: Entity not found
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /courses/{courseId}/tutors/:
    get:
      tags:
        - tutors
      operationId: getCourseTutors
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
      responses:
        200:
          description: A list of tutor users
          schema:
            type: array
            minItems: 0
            items:
              $ref: '#/definitions/UserDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /courses/{courseId}/tutors/{userId}:
    post:
      tags:
        - tutors
      operationId: addCourseTutor
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Tutor has been added successfully
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
    delete:
      tags:
        - tutors
      operationId: "deleteCourseTutor"
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
        - name: userId
          in: path
          required: true
          type: string
      responses:
        204:
          description: Tutor has been removed from the course
        404:
          description: Entity not found
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /courses/{courseId}/sessions:
    get:
      tags:
        - sessions
      operationId: getCourseSessions
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
      responses:
        200:
          description: A list of entities
          schema:
            type: array
            minItems: 0
            items:
              $ref: '#/definitions/SessionDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
    post:
      tags:
        - sessions
      operationId: addCourseSession
      security:
        - OAuth2Password: [management]
      parameters:
      - name: courseId
        in: path
        required: true
        type: string
      - in: body
        name: session
        schema:
          $ref: '#/definitions/SessionDTO'
      responses:
        201:
          description: An entity created
          schema:
            $ref: '#/definitions/SessionDTO'
        400:
          description: Problem with the request, such as a missing, invalid or type mismatched parameter
          schema:
            $ref: '#/definitions/ErrorDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /courses/{courseId}/session/{sessionId}:
    get:
      tags:
        - sessions
      operationId: getCourseSession
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
        - name: sessionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: A list of entities
          schema:
            $ref: '#/definitions/SessionDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
    put:
      tags:
        - sessions
      operationId: updateCourseSession
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
        - name: sessionId
          in: path
          required: true
          type: string
        - in: body
          name: session
          schema:
            $ref: '#/definitions/SessionDTO'
      responses:
        200:
          description: A updated entity
          schema:
            $ref: '#/definitions/SessionDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
    delete:
      tags:
        - sessions
      operationId: "deleteCourseSession"
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
        - name: sessionId
          in: path
          required: true
          type: string
      responses:
        204:
          description: Entity has been deleted sucessufly
        404:
          description: Entity not found
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /courses/{courseId}/session/{sessionId}/attendances:
    get:
      tags:
        - attendances
      operationId: getCourseSessionAttendances
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
        - name: sessionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: A list of entities
          schema:
            type: array
            minItems: 0
            items:
              $ref: '#/definitions/AttendanceDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /users/:
    get:
      tags:
        - users
      operationId: getUsers
      security:
        - OAuth2Password: [management]
      responses:
        200:
          description: A list of entities
          schema:
            type: array
            minItems: 0
            items:
              $ref: '#/definitions/UserDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /users/{userId}:
    get:
      tags:
        - users
      operationId: getUser
      security:
        - OAuth2Password: [management]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: An entity requested
          schema:
            $ref: '#/definitions/UserDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /users/{userId}/passes:
    get:
      tags:
        - passes
      operationId: getUserPasses
      security:
        - OAuth2Password: [management]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: An entities requested
          schema:
            type: array
            minItems: 0
            items:
              $ref: '#/definitions/PassDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /users/{userId}/attendances:
    get:
      tags:
        - attendances
      operationId: getUserAttendances
      security:
        - OAuth2Password: [management]
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: courseId
          in: query
          description: Filter attendances by courseId
          required: false
          type: string
      responses:
        200:
          description: A list of tutor users
          schema:
            type: array
            minItems: 0
            items:
              $ref: '#/definitions/AttendanceDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
  /courses/{courseId}/session/{sessionId}/passes/{userId}:
    post:
      tags:
        - passes
      operationId: signupForCourseSession
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
        - name: sessionId
          in: path
          required: true
          type: string
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Register for a session
          schema:
            $ref: '#/definitions/PassDTO'
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'
    delete:
      tags:
        - passes
      operationId: unsignupForCourseSession
      security:
        - OAuth2Password: [management]
      parameters:
        - name: courseId
          in: path
          required: true
          type: string
        - name: sessionId
          in: path
          required: true
          type: string
        - name: userId
          in: path
          required: true
          type: string
      responses:
        204:
          description: Deregister from a session
        404:
          description: Entity not found
        500:
          description: Internal server error, please contact support
          schema:
            $ref: '#/definitions/ErrorDTO'

definitions:
  CourseDTO:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      begins:
        type: string
        format: date
      ends:
        type: string
        format: date
  SessionDTO:
    type: object
    properties:
      id:
        type: string
      location:
        type: string
      note:
        type: string
      begins:
        type: string
        format: date-time
      ends:
        type: string
        format: date-time
  UserDTO:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
      studentId:
        type: string
      name:
        type: string
  PassDTO:
    type: object
    properties:
      id:
        type: string
        description: NFC/RFID/QR content
      session:
        $ref: '#/definitions/SessionDTO'
      generated:
        type: string
        format: date-time
  AttendanceDTO:
    type: object
    properties:
      passId:
        type: string
        description: NFC/RFID/QR content
      user: # Not used for /users/{userId}/attendances
        $ref: '#/definitions/UserDTO'
      session: # Not used for /courses/{courseId}/session/{sessionId}/attendances
        $ref: '#/definitions/SessionDTO'
      timestamp:
        type: string
        format: date-time
  ErrorDTO:
    type: object
    description: Describes a failure occured
    properties:
      timestamp:
        type: string
        format: date
      status:
        type: integer
      error:
        type: string
      exception:
        type: string
        description: A java exception class name
      message:
        type: string
      path:
        type: string