spring:
  profiles.active: dev

  datasource:
    initialize: false

  h2:
    console:
      enabled: false

server:
  contextPath: /api

logging:
  file: kleo-application.log
  level:
    org.springframework: INFO

security:
  realm: kleo-backend
  accessTokenValidity: 3600

  provider:
    tum:
      roles: STUDENT

  oauth2:
    resource:
      filter-order: 3

    clientId: kleo-client
    grandTypes: password,refresh_token

  jwt:
    signingKey: EZ4cyYpeHucVpWZjvRq5d6LaLjZfcjhkpg5nNBwn

  passes:
    keyAlgorithm: AES
    key: 80,-110,-19,65,10,92,-46,-11,-61,95,22,-1,-124,22,45,-23
    cipherAlgorithm: AES/CBC/PKCS5PADDING
    cipherAlgorithmParameterSpec: 110,-42,-8,111,75,-60,104,14,-78,63,72,70,29,-121,35,-20


ethereum:
  infura: ${ETHEREUM_INFURA}
  wallet:
    password: ${ETHEREUM_WALLET_PASSWORD}
    file: ${ETHEREUM_WALLET_FILE}
  attendanceTracker:
    address: ${ETHEREUM_ATTENDANCE_TRACKER_ADDRESS}
---

spring:
  profiles: dev

  datasource:
    initialize: true

  h2:
    console:
      enabled: true

logging:
  level:
    org.apache.catalina: WARN
    org.springframework.security: DEBUG
    org.springframework.boot.test: DEBUG
    org.springframework.test: DEBUG
    org.hibernate.validator: WARN
    eu.socialedge.hermes: DEBUG