spring:
  profiles.active: dev

  datasource:
    initialize: false

  h2:
    console:
      enabled: false

server:
  contextPath: /api

logging:
  file: kleo-application.log
  level:
    org.springframework: INFO

security:
  realm: kleo-backend
  accessTokenValidity: 3600

  provider:
    superuser:
      username: superuser
      password: c9kfgRCs2nsx
      roles: SUPERUSER
    tum:
      roles: USER

  oauth2:
    resource:
      filter-order: 3

    clientId: kleo-client
    grandTypes: password,refresh_token
    scopes: management

  jwt:
    signingKey: EZ4cyYpeHucVpWZjvRq5d6LaLjZfcjhkpg5nNBwn

---

spring:
  profiles: dev

  datasource:
    initialize: true

  h2:
    console:
      enabled: true

logging:
  level:
    org.apache.catalina: WARN
    org.springframework.security: DEBUG
    org.springframework.boot.test: DEBUG
    org.springframework.test: DEBUG
    org.hibernate.validator: WARN
    eu.socialedge.hermes: DEBUG